Made a topPage's UI/UX
devteam-d/Tic-Tac-Toe-devteam-d pull request #4
Opened 2024-11-17 18:21 UTC by k-morii-toridai

The UI/UX for the Tic Tac Toe board was refined !

2024-11-18 12:03 UTC, 777hira requested changes
jQuery読み込みの行の削除と名前の変更をお願いします

2024-11-18 12:03 UTC, 777hira commented on index.html
> +    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
jQueryを使用せずにmain.jsを作成しているのでこの行は消して大丈夫です。

2024-11-18 12:03 UTC, 777hira commented on index.html
>          <table class="board">
main.jsでboardを使っていて<table class="board">のboardを別の名前に変更可能ですか？

2024-11-18 12:11 UTC, 777hira requested changes
説明文を/**/で囲ってなかった箇所がありました。boardを別の名前に変更お願いします。

2024-11-18 12:11 UTC, 777hira commented on style.css
> -.board {
可能であればboardを別の名前に変更をお願いします

2024-11-18 16:57 UTC, k-morii-toridai commented on index.html
> +    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
レビューありがとうございます！編集後pushし直します！

2024-11-18 16:59 UTC, k-morii-toridai commented on index.html
>          <table class="board">
変更可能です！
TicTacTocBoard
または
Board
に変更してみます!

2024-11-18 17:00 UTC, k-morii-toridai commented on style.css
> -.board {
レビューありがとうございます
畏まりです！
こちらもBoardに変更しました

2024-11-19 12:17 UTC, hira77 commented on style.css
> -.board {
ありがとうございます

2024-11-19 12:17 UTC, hira77 commented on index.html
>          <table class="board">
ありがとうございます

2024-11-19 12:17 UTC, hira77 commented on index.html
> +    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
ありがとうございます。

2024-11-19 22:26 UTC, merged